# Generated by Django 5.1 on 2024-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
        ),
    ]
